on:
  workflow_dispatch:
#  pull_request:
#  schedule:
#   - cron: '0 * * * *'

jobs:
  publish_archive_job:
    environment: zulip-archive-api-script
    runs-on: ubuntu-latest
    name: A job to publish zulip-archive in GitHub pages
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run archive
      id: archive
      uses: zulip/zulip-archive@master
      with:
        zuliprc: ${{ secrets.ZULIPRC }}
        # Using the GitHub Token that is provided automatically by GitHub Actions
        # (no setup needed).
        github_token: ${{ secrets.GITHUB_TOKEN }}
        delete_history: true
        archive_branch: main
